### ISSUE TITLE
Why not include some sample code?

### ISSUE THREAD

**Issue by phlummox** [Zankoku-Okuno/ammonite#1]
It's rather hard to get an idea of the language from the README, which contains no code samples, or motivating examples showing why this language solves a problem better than a Lisp/ML/etc. - might it be worth including some?

**Comment by Zankoku-Okuno** [comment]
Wow, I haven't worked on this in so long that the readme feels like it was written by a different person. The language is incomplete and I have no intent to work on it again.

IIRC, the "new" thing w.r.t. Lisp/ML was supposed to be the vau calculus, which you can read about elsewhere. Even so, the more I looked into it, the less I thought it was likely to give a clear semantic foundation.

**Comment by phlummox** [comment]
Oops, I should've checked whether it was something still actively being worked on. Sorry! I don't know now where I got the link to the Ammonite repo from - it must have been mentioned somewhere else.

**Comment by Zankoku-Okuno** [comment]
Heh, no prob. Now I'm curious who else would have even noticed it. Even googling for "ammonite programming language" only shows up a Scala scripting library, though I did learn that Ammonite is also [an extinct Canaanite language spoken from the 9th to 5th century BCE](https://en.wikipedia.org/wiki/Ammonite_language).
